sunnypilot/sunnypilot

FEATURES.md

It would be nice to have a comprehensive list of features so users can make a more informed decision about which fork they wish to use and why. These are the features I know about, if there are more, let me know

Add Features.md for a comprehensive list of features

---

selfdrive/controls/lib/speed_limit_controller.py

fix typo and add comments

---

README.md

Luxury cars and readme minor style correction

Don’t forget luxury cars

---

selfdrive/car/toyota/interface.py

Credits to: @dragonpilot-community

Toyota TSS2 longTune

---

selfdrive/controls/controlsd.py
selfdrive/controls/lib/desire_helper.py
selfdrive/controls/lib/lateral_planner.py

User-defined lane change timers. **Nudge** lane change by default.

Lane Change Timer

---

selfdrive/loggerd/uploader.py

Disable automatic uploads of all logs while onroad/the car is on.
Thanks to community contributor @twilsonco!

Disable Onroad Uploads

---

selfdrive/car/toyota/interface.py

**Reimplementation**
- https://github.com/sunnyhaibin/sunnypilot/pull/93
Thanks to community contributor @dragonpilot-community!

Toyota TSS2 longitudinal improvements

---

selfdrive/car/hyundai/carstate.py
selfdrive/car/hyundai/interface.py
selfdrive/car/hyundai/values.py

**Description**
Parse speed limit data from CAN.
Some CAN and CAN-FD HKG cars broadcast speed limit data on CAN, via built-in navigation system or forward facing camera on the windshield.

HKG: parse speed limit

---

selfdrive/car/subaru/interface.py

This resolves permanent steering faults when the user overrides steering and then releases the steering wheel. Thanks to @martinl for this fix.
- https://github.com/martinl/panda/commit/8b7da38988a66b269a310479ed08973fb3635807
**Requires**
- https://github.com/sunnyhaibin/panda/pull/6

Subaru legacy: flip driver torque

---

selfdrive/car/subaru/interface.py

Subaru: add FW for 2019 Impreza with increased torque

---

selfdrive/car/chrysler/carcontroller.py
selfdrive/car/chrysler/interface.py
selfdrive/car/chrysler/values.py

This will allow all Rams to steer to 0 or 7 depending on the firmware

Ram: Steer to 0/7 MPH support

---

selfdrive/car/chrysler/interface.py
selfdrive/car/honda/interface.py
selfdrive/car/hyundai/interface.py
selfdrive/car/interfaces.py
selfdrive/car/mazda/interface.py
selfdrive/car/volkswagen/interface.py

Setup standard params for Custom Stock Longitudinal Control capable brands and models.

Controls: Custom Stock Longitudinal Control prerequisites

---

README.md

The [1] marker in the README mentions an old link to an old branch, so I fixed that. It should use the new recommended branch.

Update README.md | Update Recommended Link

---

CHANGELOGS.md
common/params.cc
selfdrive/car/toyota/interface.py

Some Toyota/Lexus models with TSS2 may have different experiences with the custom longitudinal tuning implemented in the previous PR:
- https://github.com/sunnyhaibin/sunnypilot/pull/108
Introducing a new toggle under "SP - Vehicles" in the built branches to allow users to use between stock or custom longitudinal tuning. Setup prerequisites for the new toggle.

Toyota longitudinal: TSS2 custom tuning behind toggle

---

selfdrive/car/toyota/interface.py

New longitudinal tuning for Toyota TSS2 models. Thanks to cfranyota's suggestion and dragonpilot-community.

Toyota longitudinal: new TSS2 tuning

---

selfdrive/navd/otisserv.py
selfdrive/navd/tpl/addr_input.tpl
selfdrive/navd/tpl/amap/index.html.tpl
selfdrive/navd/tpl/amap/index.js.tpl
selfdrive/navd/tpl/amap/key_input.tpl
selfdrive/navd/tpl/amap/style.css.tpl
selfdrive/navd/tpl/app_token_input.tpl
selfdrive/navd/tpl/body.tpl
selfdrive/navd/tpl/gmap/index.html.tpl
selfdrive/navd/tpl/gmap/index.js.tpl
selfdrive/navd/tpl/gmap/key_input.tpl
selfdrive/navd/tpl/gmap/style.css.tpl
selfdrive/navd/tpl/nav_confirmation.tpl
selfdrive/navd/tpl/public_token_input.tpl

Migrate `otisserv` to pub for Pull Request management.

Migrate `otisserv` to pub

---

selfdrive/debug/cycle_alerts.py

- Cleanup of https://github.com/sunnyhaibin/sunnypilot/pull/217

MSPA: Unused service

---

selfdrive/controls/controlsd.py
selfdrive/controls/lib/lateral_planner.py
selfdrive/controls/plannerd.py
selfdrive/debug/cycle_alerts.py

**Requires**
- https://github.com/sunnypilot/cereal/pull/9

MSPA: `lateralPlanSP` legacy support

---

selfdrive/controls/lib/lateral_planner.py

**Requires**
- https://github.com/sunnypilot/cereal/pull/10

mapd: Remove more legacy implementation

---

selfdrive/controls/controlsd.py
selfdrive/controls/lib/lateral_planner.py
selfdrive/modeld/modeld.py

**Requires**
- https://github.com/sunnypilot/cereal/pull/11

MSPA: Lat plan deprecation prerequisites

---

selfdrive/ui/translations/main_zh-CHS.ts

Translation example
- Retain hotspot/tethering state

Translations: zh-CHS example

---

selfdrive/ui/translations/main_zh-CHS.ts

Translations: Simplified Chinese

---

selfdrive/ui/translations/main_ar.ts
selfdrive/ui/translations/main_de.ts
selfdrive/ui/translations/main_fr.ts
selfdrive/ui/translations/main_ja.ts
selfdrive/ui/translations/main_ko.ts
selfdrive/ui/translations/main_pt-BR.ts
selfdrive/ui/translations/main_th.ts
selfdrive/ui/translations/main_tr.ts
selfdrive/ui/translations/main_zh-CHS.ts
selfdrive/ui/translations/main_zh-CHT.ts

This PR includes improvements in language support for our global users:
- All text elements from the latest `staging-c3` branch are now structured and available for translations.
- **Simplified Chinese** translation is now fully integrated and updated based on the latest `staging-c3` thanks to @1okko .
- https://github.com/sunnypilot/sunnypilot/pull/340
- https://github.com/sunnypilot/sunnypilot/pull/306
- In order to translate, simply open the relevant files with `linguist` and use the existing Qt translation files. Do not re-compile the source code, as recompiling may lead to the loss of necessary texts for translations.
- If you would like to contribute to the translation efforts, open a PR against the `master` branch. The sunnypilot team will promptly allocate resources to review the …

Translations: sunnypilot custom texts

---

selfdrive/car/chrysler/interface.py
selfdrive/car/ford/interface.py
selfdrive/car/gm/interface.py
selfdrive/car/honda/interface.py
selfdrive/car/hyundai/interface.py
selfdrive/car/mazda/interface.py

Reverts sunnypilot/sunnypilot#361

Revert "MADS: Map cruise main and lateral buttons to button events"

---

selfdrive/car/chrysler/interface.py
selfdrive/car/ford/interface.py
selfdrive/car/gm/interface.py
selfdrive/car/honda/interface.py
selfdrive/car/hyundai/interface.py
selfdrive/car/mazda/interface.py

MADS: Map cruise main and lateral buttons to button events

---

selfdrive/car/chrysler/carcontroller.py
selfdrive/car/honda/carcontroller.py
selfdrive/car/hyundai/carcontroller.py
selfdrive/car/interfaces.py
selfdrive/car/mazda/carcontroller.py
selfdrive/car/param_manager.py
selfdrive/car/subaru/carcontroller.py
selfdrive/car/toyota/carcontroller.py
selfdrive/car/toyota/interface.py
selfdrive/car/volkswagen/carcontroller.py
selfdrive/ui/sunnypilot/qt/offroad/settings/sunnypilot/mads_settings.cc

Part of https://github.com/sunnypilot/sunnypilot/issues/377

car: Move all live param checks to `ParamManger`

---

.gitlab-ci.yml

Improving our pipeline flow internally for the prebuilts

ci: Prebuilt public branches and update build number

---

selfdrive/car/toyota/interface.py

Introduced in https://github.com/sunnypilot/sunnypilot/pull/378

car: Fix typo with `ParamManager` variable

---

selfdrive/car/toyota/interface.py
selfdrive/controls/lib/longitudinal_mpc_lib/long_mpc.py
selfdrive/controls/lib/sunnypilot/accel_controller.py

new api: human like long control

---

selfdrive/car/tesla/carstate.py
selfdrive/car/tesla/interface.py

This should enable the `ALC: Delay with Blind Spot` toggle

Tesla: set enableBsm flag for 3 and Y

---

selfdrive/car/hyundai/interface.py

Remove device

---

selfdrive/car/toyota/interface.py
selfdrive/controls/lib/longitudinal_mpc_lib/long_mpc.py
selfdrive/controls/lib/sunnypilot/accel_controller.py

CTV 2.0: GlideTech

---

common/params.cc
selfdrive/car/toyota/carstate.py
selfdrive/ui/sunnypilot/qt/offroad/settings/vehicle_settings.cc
system/manager/manager.py

@sunnyhaibin can you find hkg signal?

Toyota: drive mode selector 

---

LICENSE.md

- https://github.com/sunnypilot/opendbc/pull/26
- https://github.com/sunnypilot/panda/pull/38

Add Custom MIT License

---

.github/workflows/ui_preview.yaml

adds the branch we are currently using as one of the targets to trigger the action of diff

ci: sunnypilot show UI diff on PRs 

---

.github/workflows/selfdrive_tests.yaml
.lfsconfig
.lfsconfig-comma
lfs-comma-pull.sh

Used to pull comma's LFS and have it downloaded on your PC so that it's then ready to be pushed to our own LFS.

LFS: Sync refs from upstream

---

Dockerfile.openpilot_base
pyproject.toml
tools/op.sh
uv.lock

Cherry picks https://github.com/sunnypilot/sunnypilot/commit/9c9b273a3e89b3de7afe3ea400a9a7c45c783723

CI: cherry pick maxime's fix for pipelines docker

---

selfdrive/ui/sunnypilot/qt/widgets/controls.h

Split from https://github.com/sunnypilot/sunnypilot/pull/885

ui: Adjust stretch factor for `ListWidgetSP`

---

selfdrive/ui/sunnypilot/qt/offroad/settings/longitudinal/speed_limit/speed_limit_policy.cc
selfdrive/ui/sunnypilot/qt/offroad/settings/longitudinal/speed_limit/speed_limit_policy.h
selfdrive/ui/sunnypilot/qt/offroad/settings/longitudinal/speed_limit/speed_limit_settings.cc
selfdrive/ui/sunnypilot/qt/offroad/settings/longitudinal/speed_limit/speed_limit_settings.h

ui: fix scrolling behavior in Speed Limit settings

---

sunnypilot/selfdrive/car/intelligent_cruise_button_management/controller.py

ICBM: allow button commands at all speeds
