sunnypilot/sunnypilot

selfdrive/ui/paint.cc
three-part PR to reposition the laneless button and make it dynamic so it works on C3 with nav mode. 
The button press only works when you press the laneless button _in nave mode_, not otherwise, but that's because all screen presses in normal (sidebar hidden) mode are hijacked to switch to nav mode.
Looks pretty good.
I also blew it up a bit.
=> dynamic laneless button for C3 (nav mode) 1/3

selfdrive/ui/ui.h
three-part PR to reposition the laneless button and make it dynamic so it works on C3 with nav mode. 
The button press only works when you press the laneless button _in nave mode_, not otherwise, but that's because all screen presses in normal (sidebar hidden) mode are hijacked to switch to nav mode.
Looks pretty good.
I also blew it up a bit.
=> dynamic laneless button 2/3

selfdrive/ui/qt/home.cc
three-part PR to reposition the laneless button and make it dynamic so it works on C3 with nav mode. 
The button press only works when you press the laneless button _in nave mode_, not otherwise, but that's because all screen presses in normal (sidebar hidden) mode are hijacked to switch to nav mode.
Looks pretty good.
I also blew it up a bit.
=> dynamic laneless button 3/3

selfdrive/ui/qt/onroad.cc
On C3, any mouse press causes the onroad gui to 3-way toggle between map, sidebar, neither, and the laneless button only responds when pressed in nav mode.
Nav is now only toggled when the mouse press is not on the laneless button.
@twilsonco
Author
twilsonco commented now
Also with this the button button works when in nav or normal (no sidebar) mode.
=> Suppress C3 Nav toggle when DLP button is pressed

selfdrive/ui/paint.cc
Also only draw laneless button if no alerts are shown, like the DM face.
=> Fix DLP button transition behavior when Nav is toggled on C3

HOW-TOS.md
`killall boardd` did not work, `pkill -f openpilot` did.
=> README: Enable Radar Tracks

selfdrive/ui/qt/onroad.cc
The compilation fails due to type mismatch and strict -werror enforcement.
=> Fix compilation error allowing boot to succeed

selfdrive/car/subaru/carstate.py
The brake_light signal is not a boolean (it is an int, 1 for true and 0 for false), which caused a crash
short drive: https://connect.comma.ai/111b7e3a9ff2341a/1646862114749/1646862349196
=> Fix crash on brake pressed on subaru forester

CHANGELOGS.md, selfdrive/common/params.cc, selfdrive/controls/lib/lane_planner.py, selfdrive/controls/lib/lateral_planner.py, selfdrive/ui/qt/widgets/sunnypilot.cc, selfdrive/ui/qt/widgets/sunnypilot.h
Couple of  notes this with this PR: 
1) I set a few params to be [ON] by default in between installs, namely:
- Training is marked as completed so don't have redo between installs.
- Terms and Conditions have been accepted.
- Turn on:
- Lane Departure Warning, 
- Right hand drive 
- Metric units.
- Enable `Quiet Drive` by default.
- Enable `SSH` by default.
2) This also implements PR: https://github.com/commaai/openpilot/commit/233a6e4a625a8ef145904522e4663177bcd3d65d
3) Visual change: Increased the font size of the +/- buttons slightly.
4) Line 55-64 in `selfdrive/controls/lib/lane_planner.py` is from DP's Camera Offset feature. I think this can be altered to update the variable without turning off and on the car (TODO) 
5) This is compatible with all hardware.
=> Feature: `CameraOffset`

README.md
Moved installation to top, added quick install instructions for comma 3, switched URL from Smiskol to installer.comma.ai
=> Update Installation instructions

selfdrive/car/toyota/carcontroller.py, selfdrive/car/toyota/toyotacan.py, selfdrive/controls/controlsd.py, selfdrive/controls/lib/drive_helpers.py
**Availability**
- Toyota/Lexus cars capable of openpilot longitudinal control
- openpilot longitudinal available cars (Experimental openpilot Longitudinal Control)
Allow set speed to increment/decrement in multiple speed units while using openpilot longitudinal control.
This may also benefits cars that support Custom Stock Longitudinal Control. Will address in a future PR.
=> Longitudinal: Reverse ACC Change

selfdrive/car/gm/carstate.py, selfdrive/car/interfaces.py, selfdrive/car/toyota/carstate.py, selfdrive/car/toyota/interface.py, selfdrive/car/toyota/values.py, selfdrive/car/volkswagen/carstate.py
Parse `Distance`/`Interval` button from the physical cruise control buttons on the steering wheel. Prerequisite of GAC and Experimental Mode toggling when using openpilot longitudinal.
=> Longitudinal: parse physical distance button

selfdrive/car/subaru/carcontroller.py, selfdrive/car/subaru/interface.py, selfdrive/car/subaru/subarucan.py
Revert legacy `ES_LKAS` counter autogeneration and disable `dashcamOnly` for Pre-Global Subaru platforms.
Thanks to community contributor @martinl!
=> Pre-Global Subaru: counter fix and disable dashcamOnly

selfdrive/mapd/README.md
This README fell through the cracks during the last major refactor/merge.
=> mapd: bring back README

selfdrive/car/subaru/values.py
Added 2019 Subaru Impreza ECU to enable vehicle recognition. Tested on fork of open pilot master on 11/4.
Validation done on successful drive with fork.
Route
Route: 78c45ff47fdd934b|2022-11-04--18-34-57
see PR https://github.com/commaai/openpilot/pull/26385
=> add engine ecu for 2019 subaru impreza

selfdrive/controls/lib/longitudinal_planner.py
Currently, when cruise control speed is set, Enhanced Speed Control (SLC, V-TSC, M-TSC) events are displayed, even on unsupported platforms (non openpilot Longitudinal Control capable cars).
Events are now no longer displayed on platforms that do not support Enhanced Speed Control.
=> Block Enhanced Speed Control events on unsupported platforms

selfdrive/car/hyundai/values.py
Add firmware for the 2019 Kia Forte Non-SCC.
Thanks to community 2019 Kia Forte Non-SCC owner AskAlice.
=> HKG: add FW versions for Kia Forte Non-SCC 2019

selfdrive/car/hyundai/interface.py
Detects smartMDPS that emits `0x2AA` to sunnypilot/openpilot. The smartMDPS must flash with the following firmware or equivalent that emits `0x2AA` on bus 0:
- [`sunnyhaibin/panda:sunnypilot_smdps`](https://github.com/sunnyhaibin/panda/tree/sunnypilot_smdps)
=> HKG: support steer to 0 with smartMDPS on certain models

selfdrive/controls/lib/speed_limit_controller.py, selfdrive/controls/lib/vision_turn_controller.py
When Speed Limit Control and/or Vision Turn Speed Control is engaged, the user manual accelerator press should not disengage the systems if the `Disengage on Accelerator Pedal` toggle is disabled.
=> Enhanced Speed Control: accelerator press state handling

selfdrive/car/chrysler/interface.py
The upstream method to check if the first 4 characters of the EPS firmware are smaller than or equal to the defined bounds to set `minEnableSpeed = 0.` would not work for some Ram DT.
Affected route: `001ccccec7a1992c|2023-06-07--21-25-45`
EPS FW: `b'21590101AA'`
Only allow `minEnableSpeed = 0.` for the EPS firmware that is known to allow enable steering at 0.
=> Ram DT: check EPS firmware explicitly to set minEnableSpeed to 0

selfdrive/navd/otisserv.py, selfdrive/navd/tpl/addr_input.tpl, selfdrive/navd/tpl/nav_confirmation.tpl
Small enhancements to the non-prime navigation web interface with the following:
Ability to select existing home/week saved destinations that were stored in param ApiCache_NavDestinations from new dropdown
Ability to add 3 other favorite destinations that are stored in param ApiCache_NavDestinations with labels
On nav_confirmation template, added the word "Set" to separate action from main page. e.g. "Set Home", "Set Work" etc.
=> nav: Local Webserver Enhancements

selfdrive/car/hyundai/interface.py, selfdrive/car/hyundai/values.py, selfdrive/car/sunnypilot_carname.json
**Checklist**
**Link to all physical parts during installation**
- [comma 3X](https://comma.ai/shop/comma-3x)
- [car harness kit](https://comma.ai/shop/car-harness)
- [Hyundai B](https://github.com/commaai/openpilot/wiki/Hyundai-Kia-Genesis#harness-guide)
Thanks to the community 2019 Hyundai Kona Non-SCC owner Quex#4164 (Discord).
=> Hyundai: Car Port for Kona 2019 Non-SCC

selfdrive/navd/otisserv.py
**Description** 
Adds ability to quickly set destinations via iOS Shortcuts or any other third party solution for non-prime users
set_destination and locations Endpoints
Added GET /locations endpoint
Added POST /set_destination endpoint
**Verification** [](Explain how you tested the refactor for regressions.)
Tested with twilsonco iOS Shortcuts and conforms with https://api.comma.ai/#navigation for both of these endpoints.
=> otisserv: `set_destination` and `locations` endpoints for non-prime users

selfdrive/car/chrysler/interface.py, selfdrive/car/ford/interface.py, selfdrive/car/gm/interface.py, selfdrive/car/honda/interface.py, selfdrive/car/hyundai/interface.py, selfdrive/car/mazda/interface.py
Map certain cruise control buttons to `car.CarState.buttonEvents`:
- Lateral button to engage factory lane centering: `altButton1`
- `CRUISE MAIN`: `altButton3`
=> MADS: Map cruise main and lateral buttons to button events

selfdrive/car/tesla/interface.py
This is an intermediate fix to allow SP to work on tesla by default (even if the user forgets to disable MADS)
Tesla has no main cruise on/off state, cruise availability is determined automatically based on vehicle speed, road detection, and brake pedal input. So this PR disables the cruise main detection for MADS to ensure it doesn't attempt to automatically engage without user input.
Without this PR, if mads is enabled, it will attempt to engage MADS as soon as the car has reached 18mph and cause a controls mismatch.
Before: bbbf82d987d681bc/00000229--3f4ce34e89/0
After: bbbf82d987d681bc/0000022c--c954640cea/0
=> Disable cruise main state detection for Tesla

selfdrive/car/tesla/carstate.py, selfdrive/car/tesla/interface.py
SP failed to start due to an import error on button states. I noticed create_mads_event was also unused.
This gets the tesla port to a working state as long as mads is disabled.
=> Remove dangling imports

selfdrive/car/card.py, selfdrive/car/chrysler/interface.py, selfdrive/car/ford/interface.py, selfdrive/car/gm/interface.py, selfdrive/car/honda/interface.py, selfdrive/car/hyundai/interface.py, selfdrive/car/interfaces.py, selfdrive/car/mazda/interface.py, selfdrive/car/nissan/interface.py, selfdrive/car/param_manager.py, selfdrive/car/subaru/interface.py, selfdrive/car/toyota/interface.py, selfdrive/car/volkswagen/interface.py
Unity custom param calls before `CarState` update is called.
Part of https://github.com/sunnypilot/sunnypilot/issues/377
=> car: Check params before car state is updated

.gitlab-ci.yml, release/ci/discord_template_notify_dev_public.json
Fixes the bug from https://github.com/sunnypilot/sunnypilot/pull/380 where the build numbers on `dev-c3` are not displaying with the new build numbers on Discord.
=> ci: Update build number on dev builds with Discord notification

HOW-TOS.md, README.md
I found that because the branch `(!)README` is so far behind, it causes GIT to store a lot of granular commit info separated +  all the git history before the branch was cleared which causes every  `git fetch` to waste a whopping 1.08GiB! 
I've moved the only thing that was missing which is the `HOW-TOS.md` to master branch and updated the `README.md` accordingly
After this is merged, we'll nuke the branch `(!)README`
=> Docs: Move HOW-TOS to `master`

selfdrive/car/hyundai/interface.py
This resolves a race condition between `madsEnabled` and stock `pcmCruise` for Hyundai. The addition of a check for `pcmCruise` status ensures that we only check for cruise available state without the cruise main button press check, preventing potential race conditions.
=> MADS: Hyundai: Skip cruise main button check with `pcmCruise`

selfdrive/car/hyundai/interface.py
The current radar parser updates at 20 Hz, which is not the same as the timestep for ESCC and camera-based SCC cars doing longitudinal (50 Hz). This change syncs the timestep for radar parser with ESCC and camera-based SCC cars.
Thanks to @ajouatom for bringing this to our attention!
=> Hyundai Longitudinal: Match stock timestep for ESCC and Camera-based SCC

selfdrive/controls/lib/latcontrol_torque.py
Simple change to NNLC and `TorqueLateralJerk`, replacing `NNFFNoLateralJerk` with `NNFFLateralJerkFactor`, i.e. making it an adjustable float rather than a bool. This will allow for better fine-tuning of lateral jerk NNLC and "TorqueLateralJerk" input.
Also includes two bugfixes, 
1. the `lat_accel_friction_factor` would be increased when there's no desired lateral jerk, but it wasn't being lowered again in case there was non-zero desired lateral jerk. This would have resulted in too-high "friction compensation" after the bug was tripped. 
2. Because `self.use_lateral_jerk` can be changed onroad, it was possible to trigger a crash due to some of the lateral jerk instance variables having not been defined inside `init()`. The fix is to define all potentially necessary instance variables in …
=> Nnlc adjustable lat jerk

.github/workflows/compile-openpilot/action.yaml, .github/workflows/tools_tests.yaml
Adds master-new to the compile-openpilot action
=> ci: Save cache for `master-new`

.github/workflows/selfdrive_tests.yaml
Allows fails for the simulator test because we don't trust it, it fails even without changes
=> ci: Skip simulator failures

.github/workflows/selfdrive_tests.yaml
Reverts sunnypilot/sunnypilot#470
This is fixed in upstream:
- https://github.com/commaai/openpilot/pull/34160
=> Revert "ci: Skip simulator failures"

.github/workflows/sunnypilot-build-model.yaml, .github/workflows/sunnypilot-build-prebuilt.yaml
This workflow automates building models from a specified upstream branch of the openpilot repository. It caches dependencies, applies necessary patches, builds the model artifacts, and uploads them for use. This setup facilitates smoother integration and testing processes.
=> CI: Add GitHub Action to build models from upstream

.github/workflows/selfdrive_tests.yaml
MacOS runners are also free on GH public repos lol
=> ci: enable macos runners again

.github/workflows/sunnypilot-build-prebuilt.yaml
Appended "-staging" and "-release" to the VERSION variable in the GitHub Actions workflow to clearly distinguish build types. This ensures clarity in versioning for staging and release environments.
=> ci: Update version identifier in workflow for staging and release

.github/workflows/selfdrive_tests.yaml
use one label for runs-on instead of multi-label and disable process-replay
=> CI: use one label for `runs-on`

sunnypilot/mads/mads.py, sunnypilot/mads/state.py, sunnypilot/mads/tests/test_mads_state_machine.py, sunnypilot/selfdrive/selfdrived/events.py
=> MADS: allow transition from Paused to Enabled at all times

sunnypilot/mads/mads.py
This reverts commit 6d516a7704410b69a2707dfcb856eba5be519f81.
`pedalPressedAlertOnly` was accidentally removed. Need tests.
=> Revert "MADS: `wrongCarMode` alert only with selfdrive enable (#931)"

selfdrive/ui/sunnypilot/qt/onroad/hud.cc
=> ui: only draw speed limit offset when speed limit is valid
